package book.javapuzzlers.ch03.p15;

/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0
 * from F:\TestRoot\apps\a1\u005cunits\include\PolicyHome.idl
 * from F://TestRoot//apps//a1//units//include//PolicyHome.idl
 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */
public class Test {
    public static void main(String[] args) {
        System.out.println("Hello, world!\u005c\u005c");
    }
}
